- case:
    train:
      dataset: [YAGO3-10]
      batch_size: [6000]
      optimizer: [Adam]
      learning_rate: [0.0015]
      neg_sample_size: [-1]
      max_epochs: [503]
      patience: [10]
    model:
      modelname: [SRLE]
      init_size: [0.001]
      rank: [600]
      sca: [0.5]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.0]
    test: [3309]


- case:
    train:
      dataset: [WN18RR]
      batch_size: [100]
      double_neg: [True]
      optimizer: [Adam]
      learning_rate: [0.00015]
      neg_sample_size: [100]
    model:
      modelname: [SRLE_linear]
      init_size: [0.001]
      rank: [40]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.00, 0.001, 0.01, 0.1, 1.0]
    test: [3309]




- case:
    train:
      dataset: [FB237]
      batch_size: [500]
      optimizer: [Adagrad]
      learning_rate: [0.02]
      neg_sample_size: [100]
    model:
      modelname: [STLE]
      init_size: [0.001]
      rank: [40]
      sca: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.00]
      weight2: [0.00]
    test: [3309]


- case:
    train:
      dataset: [FB237]
      batch_size: [500]
      optimizer: [Adagrad]
      learning_rate: [0.02]
      neg_sample_size: [100]
    model:
      modelname: [SRLE]
      init_size: [0.001]
      rank: [40]
      sca: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.00]
      weight2: [0.00]
    test: [3309]


- case:
    train:
      dataset: [FB237]
      batch_size: [500]
      optimizer: [Adagrad]
      learning_rate: [0.02]
      neg_sample_size: [100]
    model:
      modelname: [STLE_linear]
      init_size: [0.001]
      rank: [40]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.00]
      weight2: [0.00, 0.001, 0.01, 0.1, 1.0]
    test: [3309]


- case:
    train:
      dataset: [WN18RR]
      batch_size: [100]
      double_neg: [True]
      optimizer: [Adam]
      learning_rate: [0.00015]
      neg_sample_size: [100]
    model:
      modelname: [STLE_linear]
      init_size: [0.001]
      rank: [40]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.00, 0.001, 0.01, 0.1, 1.0]
    test: [3309]


- case:
    train:
      dataset: [YAGO3-10]
      batch_size: [6000]
      optimizer: [Adam]
      learning_rate: [0.001]
      neg_sample_size: [-1]
      max_epochs: [500]
      patience: [12]
    model:
      modelname: [SRLE]
      init_size: [0.001]
      rank: [600]
      sca: [0.5]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.0]
    test: [3309]




- case:
    train:
      dataset: [FB237]
      batch_size: [500]
      optimizer: [Adagrad]
      learning_rate: [0.02]
      neg_sample_size: [200]
    model:
      modelname: [STLE, STLE_base, STLE_sca, STLE_linear]
      init_size: [0.001]
      rank: [600]
      sca: [0.5]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.00]
      weight2: [0.00]
    test: [3309]


- case:
    train:
      dataset: [WN18RR]
      batch_size: [100]
      double_neg: [True]
      optimizer: [Adam]
      learning_rate: [0.00015]
      neg_sample_size: [300]
    model:
      modelname: [SRLE_sca]
      init_size: [0.001]
      rank: [600, 10, 20, 40, 80, 160, 320]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.01]
    test: [3309]







- case:
    train:
      dataset: [WN18RR]
      batch_size: [100]
      double_neg: [True]
      optimizer: [Adam]
      learning_rate: [0.00015]
      neg_sample_size: [300]
      max_epochs: [80]
    model:
      modelname: [RotE_add_v10]
      init_size: [0.001]
      rank: [600]
      sca: [0.5]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.01]
    test: [3308, 6787, 3390, 1225, 7783, 331]

- case:
    train:
      dataset: [YAGO3-10]
      batch_size: [6000]
      optimizer: [Adam]
      learning_rate: [0.001]
      neg_sample_size: [-1]
      max_epochs: [150]
      patience: [5]
    model:
      modelname: [RotE_add_v10]
      init_size: [0.001]
      rank: [600]
      sca: [0.5]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.01]
    test: [20]

- case:
    train:
      dataset: [WN18RR]
      batch_size: [100]
      double_neg: [True]
      optimizer: [Adam]
      learning_rate: [0.00015]
      neg_sample_size: [300]
    model:
      modelname: [RotE_add_v10]
      init_size: [0.001]
      rank: [600]
      sca: [0.9, 0.5, 0.1]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.0]
      weight2: [0.01]
    test: [20]


- case:
    train:
      dataset: [FB237]
      batch_size: [500]
      optimizer: [Adagrad]
      learning_rate: [0.02]
      neg_sample_size: [200]
    model:
      modelname: [RotE_add_v10]
      init_size: [0.001]
      rank: [600]
      sca: [0.9, 0.5, 0.1]
    regularizer:
      reg_name: [N3_N3]
      weight: [0.00]
      weight2: [0.00]
    test: [20]



